name: charter_localization
description: Charter localizations project, which provides local and remote translations.
version: 0.0.1
repository: https://github.com/charter-projects/charter-localization
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  slang: ^3.28.0
  slang_flutter: ^3.28.0

dev_dependencies:
  charter_analysis:
    git: https://github.com/charter-projects/charter-analysis
  flutter_test:
    sdk: flutter

flutter:
